[Variables]
Size=410

; do not change this without using the generator
NbBands=10

BackgroundColor=222222aa

BorderWidth=5
BorderColor=222222aa

GridWidth=2
GridColor=DDDDDD88

PointSize=10
LineWidth=10
CloseLine=1

LabelOffset=50
LabelSize=10
LabelColor=eeeeee

; for left-right
PointColorLeft=2D55C1
PointColorRight=FF5555 
LineColorLeft=3D85C166 
LineColorRight=DD719566

; for sum
LineAlpha=100
MiddlePoint=0.7
Color1R=0
Color1G=153
Color1B=33
Color2R=255
Color2G=157
Color2B=0
Color3R=255
Color3G=0
Color3B=30