/*!
 * @name NylasMail Generator
 * @description Used to generate N Mailbox skins
 * @usage `node generator.js 3`
 * @copyright 2018 Damien "Mistic" Sorel (http://www.strangeplanet.fr)
 * @license MIT (http://opensource.org/licenses/MIT)
 */

const fs = require('fs');

const nb = process.argv[2];

if (!nb || nb != parseInt(nb)) {
  throw 'Missing number of skins';
}

for (let i = 1; i <= nb; i++) {
  const name = `Mailbox${i}`;
  const content = skin(i);
  
  if (!fs.existsSync(name)){
      fs.mkdirSync(name);
  }
  
  fs.writeFileSync(`${name}/${name}.ini`, content);
}

console.log(`${nb} mailboxes created`);

function skin(i) {
  return `# DO NOT EDIT THIS FILE
# Put your preferences in the main Variables.inc file

[Rainmeter]
Update=1000
SkinWidth=250
SkinHeight=50

[Metadata]
Name=NylasMail
Author=Mistic
License=MIT
Information=Display new mail counts with Nylas API
Version=1.0.0

[Variables]
@include=..\\Variables.inc

[TextStyle]
FontColor=0,0,0
FontFace=Source Sans Pro
FontSize=12
AntiAlias=1

[TextStyleBold]
FontWeight=700

[mMailCountTick]
Measure=Calc
UpdateDivider=60
OnUpdateAction=[!CommandMeasure mMailCount "Run"]

[mMailCount]
Measure=Plugin
Plugin=RunCommand
Parameter=curl -s "https://#Token${i}#@api.nylas.com/threads?in=inbox&view=count&unread=true"
OutputType=ANSI
RegExpSubstitute=1
Substitute='"count": ':"","{":"","}":""," ":"","#CRLF#":"","^$":"0"
IfMatch=^0$
IfMatchAction=[!HideMeter MailBadge][!SetOption MailCount Text "No new message"]
IfNotMatchAction=[!ShowMeter MailBadge][!SetOption MailCount Text "%1 new messages"]

[mBlink]
Measure=Calc
Formula=mBlink = 0 ? 255 : (1 - #BadgeBlink${i}#) * 255

[Background]
Meter=Image
ImageName=#@#Images\\background.png
ImageAlpha=150
X=0
Y=0
W=250
H=50

[MailIcon]
Meter=Image
ImageName=#@#Images\\icon-#Icon${i}#.png
X=7
Y=7
W=30
H=30

[MailBadge]
Meter=Roundline
X=0R
Y=3r
Solid=1
LineLength=6
AntiAlias=1
LineColor=#BadgeColor${i}#,[mBlink]
DynamicVariables=1

[MailText]
Meter=String
Text=#Email${i}#
MeterStyle=TextStyle
X=45
Y=5
W=200

[MailCount]
Meter=String
MeasureName=mMailCount
Text="No new message"
MeterStyle=TextStyle | TextStyleBold
X=0r
Y=20
W=200
`;
}
