## How to get your token
# 1. Register on https://dashboard.nylas.com
# 2. Go to "Accounts" and add your email credentials
# 3. Copy the Token

## Available icons
# - gmail
# - inbox
# - white
# - yellow
# - plane1
# - plane2

[Variables]

# Mailbox 1
Token1=
Email1=
Icon1=white
BadgeColor1=255,0,0
BadgeBlink1=1

# Mailbox 2
Token2=
Email2=
Icon2=white
BadgeColor2=255,0,0
BadgeBlink2=1

# Mailbox 3
Token3=
Email3=
Icon3=white
BadgeColor3=255,0,0
BadgeBlink3=1
